title: Stuart Lau
# tagline: Here is personal website of Stuart Lau. Powered by Jekyll, based on the Minimal Mistakes theme.
# description: Two roads diverged in woods, I took the one less traveled by.
#Comment out url when working locally to resolve base urls correctly
url: https://stuartlau.github.io

# Owner/author information
owner:
  name: Stuart Lau
  avatar: about-SL-sketch.jpg
  bio: Je pense, donc je suis.
  email: stuart8@126.com
  # cv: https://stuartlau.github.io/file/CV-HanlinCAI.pdf
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # twitter: yourID
  # github: StuartLau
  linkedin: stuartlau
  # bilibili: 594030035
  # researchgate: https://www.researchgate.net/profile/Hanlin-Cai
  # zhihu: https://www.zhihu.com/people/chlire
  # facebook: caihanlin2002
  instagram: surelau
  xiaohongshu: 5dc678040000000001001e92
  douban: shuoleo
  # lastfm:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: ""

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links: []

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: stuartlau

engagement:
  like:
    enabled: true
    provider: "countapi"
    namespace: "stuartlau-github-io"
  subscribe:
    enabled: true
    url: ""
  share:
    enabled: true
  giscus:
    enabled: true
    repo: "stuartlau/stuartlau.github.io"
    repo_id: "R_kgDOOf5c7g"
    category: "Announcements"
    category_id: "DIC_kwDOOf5c7s4Cz_Oz"
    mapping: "pathname"
    strict: 0
    reactions_enabled: 1
    emit_metadata: 0
    input_position: "top"
    theme: "preferred_color_scheme"
    lang: "en"

# Related posts configuration
related_posts:
  enabled: true
  title: "You might also enjoy"
  max: 3  # Maximum number of related posts to show
  min_tags: 1  # Minimum number of common tags required

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]
